services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft-server
    environment:
      - EULA=TRUE
      - VERSION=LATEST
      - TYPE=PAPER # Recomendado para mejor rendimiento
      - MEMORY=2G # Ajusta seg√∫n tu RAM disponible
      - MAX_PLAYERS=20 
      - ONLINE_MODE=TRUE # Cambiar a FALSE si necesitas modo offline (no premium)
      - OPS=ShadeTheWitcher # Lista separada por comas de admins: nombre_usuario1,nombre_usuario2
      - MOTD= Servidor de Minecraft byShade # Mensaje que sale en la lista de servidores
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    restart: unless-stopped
    stdin_open: true # Necesario para interactuar con la consola
    tty: true        # Necesario para interactuar con la consola
